name_or_path: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
tokenizer_name_or_path: null
archive: null
block_name: LlamaDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: null
reference_dtype: float16
